sudo: false
language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
cache: cargo
before_script:
- |
  (cargo-install-update --version  && cargo install-update cargo-update) || cargo install cargo-update &&
  (rustfmt --version && cargo install-update rustfmt) || cargo install rustfmt &&
  (cargo-prune --version && cargo install-update cargo-prune) || cargo install cargo-prune
script:
- |
  cargo fmt -- --write-mode=diff
  cargo build --release
  cargo test --release
