sudo: false
language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
cache: cargo
before_script: (cargo install-update cargo-update && cargo install-update rustfmt || cargo install rustfmt && cargo install cargo-update)
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build --release &&
  cargo test --release
