sudo: false
language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
cache: cargo
env:
  global:
    - PATH=$PATH:$HOME/.cargo/bin
before_script:
- |
  (which cargo-install-update   && cargo install-update cargo-update) || cargo install cargo-update &&
  (which rustfmt && cargo install-update rustfmt) || cargo install rustfmt &&
  (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
script:
- |
  cargo fmt -- --write-mode=diff
  cargo test --release
