[package]
authors = ["Hugo Freire <hfreire@abajar.com>"]
description = "Implementation of NeuroEvolution of Augmenting Topologies NEAT http://nn.cs.utexas.edu/downloads/papers/stanley.ec02.pdf with a Continuous-Time Recurrent Neural Networks"
documentation = "https://github.com/TLmaK0/rustneat"
homepage = "https://github.com/TLmaK0/rustneat"
keywords = ["neuro", "evolution", "neat", "genetic", "algorithm"]
license = "MIT"
name = "rustneat"
repository = "https://github.com/TLmaK0/rustneat"
version = "0.2.0"

[dependencies]
conv = "0.3.2"
crossbeam = "0.2"
lazy_static = "0.2.2"
num_cpus = "1.0"
rand = "0.4"
rulinalg = "0.3.4"
rusty_dashed = "0.2.1"
rustc-serialize = "0.3.21"
open = "1.2.1"

[dependencies.clippy]
optional = true
version = "0.0.103"

[features]
default = []
telemetry = []
