[package]
name = "rustneat"
version = "0.1.4"
authors = ["Hugo Freire <hfreire@abajar.com>"]
description = "Implementation of NeuroEvolution of Augmenting Topologies NEAT http://nn.cs.utexas.edu/downloads/papers/stanley.ec02.pdf"

license = "MIT"
license-file = "LICENSE.md"

documentation = "https://github.com/TLmaK0/rustneat"
homepage = "https://github.com/TLmaK0/rustneat"
repository = "https://github.com/TLmaK0/rustneat"

keywords = ["neuro", "evolution", "neat", "genetic", "algorithm"]

[dependencies]
rand = "0.3"
conv = "0.3.2"
uuid = "0.1"
lazy_static = "0.1.*"
collenchyma = { version = "0.0.8", default-features = false }
collenchyma-nn = { version = "0.3.4", default-features = false }
collenchyma-blas = { version = "0.2.0", default-features = false }

[features]
default = ["native"]
native  = ["collenchyma/native", "collenchyma-blas/native", "collenchyma-nn/native"]
cuda    = ["collenchyma/cuda", "collenchyma-blas/cuda", "collenchyma-nn/cuda"]
opencl  = ["collenchyma/opencl", "collenchyma-blas/opencl", "collenchyma-nn/opencl"]
