[package]
name = "rustneat"
version = "0.1.1"
authors = ["Hugo Freire <hfreire@abajar.com>"]
description = "Implementation of NeuroEvolution of Augmenting Topologies NEAT http://nn.cs.utexas.edu/downloads/papers/stanley.ec02.pdf"
license = "MIT"

[dependencies]
rand = "0.3"
conv = "0.3.2"
uuid = "0.1"
